---
name: Build Wyoming Piper GLaDOS Image

on:
  workflow_call:
    inputs:
      base_piper_version:
        description: 'Base version of Wyoming Piper image to use'
        required: true
        type: string
      push_image:
        description: 'Whether to push the built image to the registry'
        required: false
        type: boolean
        default: false

env:
  IMAGE_NAME: wyoming-piper-glados
  DOCKER_REGISTRY: ghcr.io
  IMAGE_VERSION: ${{ inputs.base_piper_version }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ inputs.push_image }}
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
