---
name: Pull Request

on:
  push:
    branches:
      - master

jobs:
  lint:
    permissions:
      contents: read
    uses: ./.github/workflows/lint.yaml
  build:
    permissions:
      contents: read
      packages: write
    needs: lint
    uses: ./.github/workflows/build-image.yaml
    with:
      base_piper_version: '1.6.2'
      push_image: true
