---
name: Pull Request

on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    permissions:
      contents: read
    uses: ./.github/workflows/lint.yaml
  build:
    permissions:
      contents: read
    needs: lint
    uses: ./.github/workflows/build-image.yaml
    with:
      base_piper_version: '1.6.2'
      run_number: ${{ github.run_number }}
